.TH OpenTorpedo "6" "September 2011" "OpenTorpedo 0.8"
.SH NAME
OpenTorpedo \- modern submarine tactical simulator
.SH SYNOPSIS
\fBOpenTorpedo\fR [\fIoptions\fR]
.SH DESCRIPTION
OpenTorpedo is a submarine simulation (subsim) which tries to emulate the
behaviour of modern submarines. The player is placed in command of a 
submarine and is able to move about in a deep ocean environment.
.SH OPTIONS
.TP
\fB\-w\fR
Run in windowed mode (default)
.TP
\fB\-f\fR
Run in full screen
.TP
\fB\-s\fR
Enable sound effects
.TP
\fB\-v\fR
Display version number and exit
.TP
\fB\-h\fR
Display help and exit
.TP
\fB\-m\fR \fImission\fR
Load a specific mission
.SH AUTHOR
OpenTorpedo was written by Jesse Smith <jessefrgsmith@yahoo.ca>, built upon the
work of LinuxSSN's authors (Michael Bridak <michael.bridak@verizon.net> and
Rick McDaniel <rickeym@swbell.net>).
.PP
This manual page was written by Vincent Cheng <Vincentc1208@gmail.com>,
for the Debian project (and may be used by others).
